var flirt = [
	"You must be French because you smell like Pepe Le Pew, you dirty bitch.",
	"Yo baby, your ass is out this world! It looks like a fucking alien.",
	"Suck my dick.",
	"Somebody call the cops! This whore stole my wallet.",
	"The eggs are burnt, you whore.",
	"Your mother should've swallowed.",
	"No, I'm not going to kiss you! You just ate my ass, what the fuck...",
	"I've been cripplingly alone but if I ever settle for you, I'll blow my fucking brains out.",
	"Wow, what a waste of air you are.",
	"Your cock is so small that i'd be better off fucking the Boss Baby.",
	"Please fuck my wife. It's the only way I get off anymore.",
	"Look, I know we're cousins but you know what they say! When in Alabama!",
	"Hi, nice to meet you! I eat ass.",
	"I never suck dick on the first date, but luckily for you, I wouldn't even consider that pinky a dick.",
	"Lemme suck on your toes like a Garra fish.",
	"I'll have you know my dog thinks my dick is big.",
	"Is your ass jealous of the amount of shit that just came out of your mouth?",
	"Roses are red, violets are blue, I have 5 fingers, the 3rd ones for you.",
	"Fuck, this doesn't usually happen. Just like touch it or kiss it or something.",
	"Show me how you won the county fair's Hot Dog eating contest, baby.",
	"I would rather rip out all of my teeth and hot glue them back in than spend another minute with you.",
	"I want a divorce.",
	"Wow! With rocking tits like that, I wasn't expecting the penis.",
	"No homo bro but those track shorts really compliment you.",
	"My thang swang more than the track team on Juno.",
	"What they say is true, ya know? That black is better? At least, my wife thought so.",
	"Somebody call the cops, because its got to be illegal to look that good!",
	"What has 36 teeth and holds back the Incredible Hulk? My zipper.",
	"If nothing lasts forever, will you be my nothing?",
	"Are you parking ticket because you have fine written all over you.",
	"Do you happen to have any Band-Aids? I skinned my knee when I fell for you.",
	"My lips are like skittles. Wanna taste the rainbow?",
	"Ma'am, you're in violation of fire code. You're too hot for us to ever possibly handle.",
	"Damn you got a big ass!",
	"You're looking thiccer than a bowl of oatmeal.",
	"I don't have a lot of Ho Ho Ho's, baby. You're the only one I want jingling my bells.",
	"Wanna Sprite Cranberry?",
	"Girl you're sweet as candy, can I taste you 'Now And Later'?",
	"You like a bottle a maple syrup....THICK.",
	"Honey just by seeing you from behind I know you're a well-rounded person.",
	"You're so good-looking I actually just forgot my pick up line.",
	"Hey girl, are you from Japan? Cause you got anime-zing body.",
	"Are you from Africa? Cause I wanna know Kenya suck this dick?",
	"You’re that 'Nothing' when people ask me what i'm thinking about.",
	"I think your hand looks heavy. Would you like me to hold it for you?",
	"Apart from being sexy, what do you do for a living?",
	"Are you a magician? Because whenever I look at you, everyone else disappears!",
	"You look so sweet you're giving me a toothache.",
	"There must be something wrong with my eyes, I can't take them off you.",
	"Boy you so fine, I wanna make you mine."
	]
	
	function newFlirt() {
		var randomNumber = Math.floor(Math.random() * (flirt.length));
	document.getElementById("flirtDisplay").innerHTML = flirt[randomNumber];
	}
	